id: Checkpoint - Block URL
version: 15
contentitemexportablefields:
  contentitemfields:
    packID: CheckpointFirewall
    itemVersion: 2.1.6
    fromServerVersion: 5.0.0
    toServerVersion: ""
vcShouldKeepItemLegacyProdMachine: false
name: Checkpoint - Block URL
description: |-
  This playbook blocks URLs using Checkpoint Firewall through Custom URL Categories.
  The playbook checks whether the input URL category already exists, and if the URLs are a part of this category. Otherwise, it will create the category, block the URLs, and publish the configuration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 752c8366-9954-40bb-81f7-25944a795ef9
    type: start
    task:
      id: 752c8366-9954-40bb-81f7-25944a795ef9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 540,
          "y": -950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 637bf853-b339-434f-82f5-ad53762b2e89
    type: playbook
    task:
      id: 637bf853-b339-434f-82f5-ad53762b2e89
      version: -1
      name: Checkpoint - Publish&Install configuration
      description: |
        Publish the Checkpoint Firewall configuration, also, install policy over all the gateways are available  .
      playbookName: Checkpoint - Publish&Install configuration
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      auto_logout:
        simple: "True"
      checkpoint_error_handling:
        simple: ${inputs.checkpoint_error_handling}
      discard_changes:
        simple: ${inputs.discard_changes}
      install_policy:
        simple: ${inputs.install_policy}
      policy_package:
        simple: ${inputs.policy_package}
      sid:
        simple: ${CheckPoint.Login.session-id}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 15efb195-e8c1-4309-82f9-ac5b71f89872
    type: title
    task:
      id: 15efb195-e8c1-4309-82f9-ac5b71f89872
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 540,
          "y": 1760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 0bd83706-906f-4bc5-87d5-c78e1e7f5f87
    type: regular
    task:
      id: 0bd83706-906f-4bc5-87d5-c78e1e7f5f87
      version: -1
      name: Checkpoint application site append URLs
      description: Added the URL as  application site in Checkpoint firewall.
      script: '|||checkpoint-application-site-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      identifier:
        simple: ${inputs.URL}
      name:
        simple: XSOAR-${inputs.URL}
      primary_category:
        simple: ${inputs.URL_application_site_category}
      session_id:
        simple: ${CheckPoint.Login.session-id}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: a25d05d5-5d23-4d8b-856d-015b3bd5862d
    type: regular
    task:
      id: a25d05d5-5d23-4d8b-856d-015b3bd5862d
      version: -1
      name: Checkpoint login and get session id
      description: Login to Checkpoint to get uniq session id.
      script: '|||checkpoint-login-and-get-session-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": -655
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: f3c018de-8713-4953-8caa-f3081378a497
    type: condition
    task:
      id: f3c018de-8713-4953-8caa-f3081378a497
      version: -1
      name: Is Checkpoint firewall enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: inList
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: CheckPointFirewall,CheckPointFirewall_v2
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 540,
          "y": -825
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 6284f556-ab72-4787-8586-a79422d3d4b1
    type: regular
    task:
      id: 6284f556-ab72-4787-8586-a79422d3d4b1
      version: -1
      name: Checkpoint logout
      description: Logout with specific SID from Checkpoint firewall.
      script: '|||checkpoint-logout'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      session_id:
        simple: ${CheckPoint.Login.session-id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: c496f3a1-0302-4487-820e-b59488ba2ac1
    type: condition
    task:
      id: c496f3a1-0302-4487-820e-b59488ba2ac1
      version: -1
      name: Was the application site URL added?
      description: Validate if URL was added to application site successfully.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CheckPoint
                accessor: ApplicationSite
            iscontext: true
    view: |-
      {
        "position": {
          "x": 270,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 0ee35904-5636-4247-84dd-788fcc94df9e
    type: regular
    task:
      id: 0ee35904-5636-4247-84dd-788fcc94df9e
      version: -1
      name: Print added URL error
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      value:
        simple: 'The URL was not added to application site during error. '
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": 1025
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 739a1d5a-d361-47a9-8869-2ac6e480eb64
    type: condition
    task:
      id: 739a1d5a-d361-47a9-8869-2ac6e480eb64
      version: -1
      name: Is the URL application site category exist?
      description: Validate if URL application site category is exists.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${CheckPoint.ApplicationSiteCategory.name}
            iscontext: true
          right:
            value:
              simple: inputs.URL_application_site_category
            iscontext: true
    view: |-
      {
        "position": {
          "x": 270,
          "y": -320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: aabcbca8-e6ab-4e1b-8dc9-55027b523d19
    type: playbook
    task:
      id: aabcbca8-e6ab-4e1b-8dc9-55027b523d19
      version: -1
      name: Checkpoint - Publish&Install configuration
      description: |
        Publish the Checkpoint Firewall configuration, also, install policy over all the gateways are available  .
      playbookName: Checkpoint - Publish&Install configuration
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      auto_logout:
        simple: "False"
      checkpoint_error_handling:
        simple: ${inputs.checkpoint_error_handling}
      discard_changes:
        simple: ${inputs.discard_changes}
      install_policy:
        simple: ${inputs.install_policy}
      policy_package:
        simple: ${inputs.policy_package}
      sid:
        simple: ${CheckPoint.Login.session-id}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": -10,
          "y": 460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 03dc594c-c844-4fa4-8b0f-01788a808b3f
    type: regular
    task:
      id: 03dc594c-c844-4fa4-8b0f-01788a808b3f
      version: -1
      name: Add URL category
      description: Add URL application site category in Checkpoint firewall.
      script: '|||checkpoint-application-site-category-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      identifier:
        simple: ${inputs.URL_application_site_category}
      session_id:
        simple: ${CheckPoint.Login.session-id}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": -140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: cf5f8fb4-12b4-4940-8814-b787d76eb876
    type: regular
    task:
      id: cf5f8fb4-12b4-4940-8814-b787d76eb876
      version: -1
      name: Checkpoint app site category
      description: Get application site category  to check if the category already
        exist.
      script: '|||checkpoint-application-site-category-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      identifier:
        simple: ${inputs.URL_application_site_category}
      session_id:
        simple: ${CheckPoint.Login.session-id}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 270,
          "y": -490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: fa43eea8-11cd-44d5-8929-326f1ca64434
    type: regular
    task:
      id: fa43eea8-11cd-44d5-8929-326f1ca64434
      version: -1
      name: Print added URL Category error
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      value:
        simple: There was a problem to add the URL Category.
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -320,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: f08aa17b-4127-4aa2-8702-129292de3973
    type: condition
    task:
      id: f08aa17b-4127-4aa2-8702-129292de3973
      version: -1
      name: Was URL category added successfully?
      description: Validate if URL was added successfully in Checkpoint firewall.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: ${CheckPoint.ApplicationSiteCategory}
            iscontext: true
    view: |-
      {
        "position": {
          "x": -10,
          "y": 20
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 5a2510e1-95ab-46ce-8d66-19129a2849f6
    type: condition
    task:
      id: 5a2510e1-95ab-46ce-8d66-19129a2849f6
      version: -1
      name: Is action manual handling enabled?
      description: if action manual handling enable, the Playbook will stop in favor
        of further manual handling.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.block_URL_error_handling
            iscontext: true
          right:
            value:
              simple: Stop
    view: |-
      {
        "position": {
          "x": -320,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: e56d12bd-27a4-4c85-8b16-f4096daa642e
    type: regular
    task:
      id: e56d12bd-27a4-4c85-8b16-f4096daa642e
      version: -1
      name: Fix error and publish manually
      description: User manually add resolve .
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -320,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2775,
        "width": 1240,
        "x": -320,
        "y": -950
      }
    }
  }
inputs:
- key: install_policy
  value:
    simple: "True"
  required: true
  description: Input True / False for playbook to continue install policy process
    for checkpoint Firewall.
  playbookInputQuery: null
- key: URL
  value: {}
  required: true
  description: An array of URL to block.
  playbookInputQuery: null
- key: policy_package
  value:
    simple: Standard
  required: true
  description: The name of the policy package to be installed.
  playbookInputQuery: null
- key: URL_application_site_category
  value:
    simple: Suspicious
  required: true
  description: URL category object name.  The category to add URL into.
  playbookInputQuery: null
- key: checkpoint_error_handling
  value:
    simple: Stop
  required: true
  description: |-
    In case one of the actions for publish/install policy fails due to issues on the Checkpoint side, This input will determine whether the playbook will continue or stop for manual review. Also, in case of Continue the session id will logout and all changes will discard.
    Values can be "Continue" or "Stop".
    The default value will be "Stop".
  playbookInputQuery: null
- key: block_URL_error_handling
  value:
    simple: Stop
  required: true
  description: |-
    In case one of the actions for block URL playbook fails due to issues on the Checkpoint side, This input will determine whether the playbook will continue or stop for manual review. Also, in case of Continue the session id will logout and all changes will discard.
    Values can be "Continue" or "Stop".
    The default value will be "Stop".
  playbookInputQuery: null
outputs: []
