name: Review Release Notes
on: pull_request

jobs:
  release_notes_review:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements-py3.txt
      - name: Review Release Notes
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Starting docs review"
          cd Utils/github_workflow_scripts
          python ./run_docs_review.py --changed_files $changed_files
          echo "Finished docs review"